-- 车型信息表
CREATE TABLE IF NOT EXISTS `car_info` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `info_id` VARCHAR(64) NOT NULL COMMENT '车型唯一标识',
    `brand` VARCHAR(64) DEFAULT NULL COMMENT '品牌',
    `model_name` VARCHAR(128) DEFAULT NULL COMMENT '型号名称',
    `model_year` INT DEFAULT NULL COMMENT '年款',
    `version` VARCHAR(128) DEFAULT NULL COMMENT '版本描述',
    `full_name` VARCHAR(256) DEFAULT NULL COMMENT '全称',
    `vehicle_type` VARCHAR(32) DEFAULT NULL COMMENT '车辆类型',
    `fuel_type` VARCHAR(32) DEFAULT NULL COMMENT '燃油类型',
    `seat_count` INT DEFAULT NULL COMMENT '座位数',
    `displacement` DECIMAL(4,1) DEFAULT NULL COMMENT '排量',
    `motor_power` DECIMAL(8,2) DEFAULT NULL COMMENT '电机功率',
    `range_km` INT DEFAULT NULL COMMENT '续航里程',
    `guide_price` DECIMAL(12,2) DEFAULT NULL COMMENT '官方指导价',
    `color_options` VARCHAR(512) DEFAULT NULL COMMENT '车身颜色选项',
    `dimensions` VARCHAR(64) DEFAULT NULL COMMENT '车身尺寸',
    `wheelbase` INT DEFAULT NULL COMMENT '轴距',
    `manufacturer` VARCHAR(128) DEFAULT NULL COMMENT '生产厂商',
    `status` VARCHAR(32) DEFAULT '在售' COMMENT '车型状态',
    `image_url` VARCHAR(512) DEFAULT NULL COMMENT '车型图片URL',
    `description` TEXT DEFAULT NULL COMMENT '车型描述',
    `remark` TEXT DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`)
) COMMENT='车型信息表';

-- 我的车辆信息表
CREATE TABLE IF NOT EXISTS `my_car` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `car_id` VARCHAR(64) NOT NULL COMMENT '车辆唯一标识',
    `user_id` VARCHAR(64) DEFAULT NULL COMMENT '用户ID',
    `car_info_id` VARCHAR(64) DEFAULT NULL COMMENT '关联的车型信息ID',
    `nickname` VARCHAR(128) DEFAULT NULL COMMENT '车辆昵称',
    `full_name` VARCHAR(256) DEFAULT NULL COMMENT '车辆全称',
    `image_url` VARCHAR(512) DEFAULT NULL COMMENT '车辆图片URL',
    `order_id` VARCHAR(64) DEFAULT NULL COMMENT '关联订单ID',
    `plate_number` VARCHAR(32) NOT NULL COMMENT '车牌号',
    `color` VARCHAR(32) DEFAULT NULL COMMENT '车辆颜色',
    `vin` VARCHAR(32) DEFAULT NULL COMMENT '车辆识别代号',
    `engine_number` VARCHAR(64) DEFAULT NULL COMMENT '发动机号',
    `purchase_date` DATE DEFAULT NULL COMMENT '购买日期',
    `purchase_price` DECIMAL(15,2) DEFAULT NULL COMMENT '购买价格',
    `mileage` INT DEFAULT 0 COMMENT '行驶里程',
    `register_date` DATE DEFAULT NULL COMMENT '注册日期',
    `insurance_expire_date` DATE DEFAULT NULL COMMENT '保险到期日',
    `inspection_expire_date` DATE DEFAULT NULL COMMENT '年检到期日',
    `remark` TEXT DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`)
) COMMENT='我的车辆信息表';

-- 车辆订单表
CREATE TABLE IF NOT EXISTS `car_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` VARCHAR(64) NOT NULL COMMENT '订单唯一标识',
    `user_id` VARCHAR(64) DEFAULT NULL COMMENT '用户ID',
    `car_id` VARCHAR(64) DEFAULT NULL COMMENT '关联车辆ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单编号',
    `order_type` VARCHAR(32) DEFAULT NULL COMMENT '订单类型',
    `order_status` VARCHAR(32) DEFAULT '待支付' COMMENT '订单状态',
    `brand` VARCHAR(64) DEFAULT NULL COMMENT '车辆品牌',
    `model` VARCHAR(128) DEFAULT NULL COMMENT '车辆型号',
    `color` VARCHAR(32) DEFAULT NULL COMMENT '车辆颜色',
    `vin` VARCHAR(32) DEFAULT NULL COMMENT '车辆VIN码',
    `seller_name` VARCHAR(256) DEFAULT NULL COMMENT '卖家或经销商名称',
    `seller_contact` VARCHAR(128) DEFAULT NULL COMMENT '卖家或经销商联系方式',
    `vehicle_price` DECIMAL(15,2) DEFAULT NULL COMMENT '车辆价格',
    `purchase_tax` DECIMAL(15,2) DEFAULT NULL COMMENT '购置税',
    `insurance_fee` DECIMAL(15,2) DEFAULT NULL COMMENT '保险费用',
    `other_fee` DECIMAL(15,2) DEFAULT NULL COMMENT '其他费用',
    `total_amount` DECIMAL(15,2) DEFAULT NULL COMMENT '订单总金额',
    `discount_amount` DECIMAL(15,2) DEFAULT NULL COMMENT '优惠金额',
    `actual_amount` DECIMAL(15,2) DEFAULT NULL COMMENT '实际支付金额',
    `payment_method` VARCHAR(32) DEFAULT NULL COMMENT '付款方式',
    `order_date` DATE DEFAULT NULL COMMENT '订单日期',
    `delivery_date` DATE DEFAULT NULL COMMENT '交付日期',
    `remark` TEXT DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`)
) COMMENT='车辆订单表';
