CREATE TABLE IF NOT EXISTS `knowledge_document` (
    `doc_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '文档ID',
    `doc_title` VARCHAR(1024) NOT NULL COMMENT '文档标题',
    `upload_user` VARCHAR(255) NULL COMMENT '上传用户',
    `doc_url` VARCHAR(2048) NULL COMMENT '文档URL',
    `converted_doc_url` VARCHAR(2048) NULL COMMENT '转换后的文档URL',
    `expire_date` DATE NULL COMMENT '文档失效日期',
    `status` VARCHAR(32) NOT NULL COMMENT '状态',
    `accessible_by` VARCHAR(1024) NULL COMMENT '可见范围',
    `description` VARCHAR(512) NULL COMMENT '文档描述',
    `knowledge_base_type` VARCHAR(32) NULL COMMENT '知识库类型',
    `extension` TEXT NULL COMMENT '扩展字段',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `lock_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`doc_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_status_doc_id` (`status`, `doc_id`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识文档表';

CREATE TABLE IF NOT EXISTS `knowledge_segment` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '片段ID',
    `text` LONGTEXT NOT NULL COMMENT '文本内容',
    `chunk_id` VARCHAR(255) NULL COMMENT '分片ID',
    `metadata` VARCHAR(2048) NULL COMMENT '元数据',
    `document_id` BIGINT NOT NULL COMMENT '所属文档ID',
    `chunk_order` INT NOT NULL COMMENT '顺序',
    `embedding_id` VARCHAR(255) NULL COMMENT '嵌入ID',
    `status` VARCHAR(255) NULL COMMENT '状态',
    `skip_embedding` INT NULL COMMENT '是否跳过嵌入生成',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `lock_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_document_id` (`document_id`),
    INDEX `idx_document_id_chunk_order` (`document_id`, `chunk_order`),
    INDEX `idx_document_status_skip` (`document_id`, `status`, `skip_embedding`),
    INDEX `idx_status` (`status`),
    INDEX `idx_chunk_id` (`chunk_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识片段表';

CREATE TABLE IF NOT EXISTS `table_meta` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `table_name` VARCHAR(128) NOT NULL COMMENT '表名',
    `description` VARCHAR(512) NULL COMMENT '表描述',
    `create_sql` TEXT NULL COMMENT '建表语句',
    `columns_info` TEXT NULL COMMENT '字段信息',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `lock_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_table_name` (`table_name`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='表元数据表';

CREATE TABLE IF NOT EXISTS `chat_conversation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话唯一标识',
    `user_id` VARCHAR(64) NOT NULL COMMENT '用户ID',
    `title` VARCHAR(512) NULL COMMENT '会话标题',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `lock_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI对话会话表';

CREATE TABLE IF NOT EXISTS `chat_message` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `message_id` VARCHAR(64) NOT NULL COMMENT '消息唯一标识',
    `conversation_id` VARCHAR(64) NOT NULL COMMENT '所属会话ID',
    `type` VARCHAR(32) NOT NULL COMMENT '角色',
    `content` LONGTEXT NULL COMMENT '消息内容',
    `transform_content` LONGTEXT NULL COMMENT '改写后的内容',
    `token_count` INT NULL COMMENT 'Token数量',
    `model_name` VARCHAR(128) NULL COMMENT '使用的模型名称',
    `rag_references` JSON NULL COMMENT 'RAG引用内容JSON数组',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `lock_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    `metadata` JSON NULL COMMENT '扩展元数据',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_message_id` (`message_id`),
    INDEX `idx_conversation_id` (`conversation_id`),
    INDEX `idx_create_time` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI对话消息表';

CREATE TABLE IF NOT EXISTS `ingestion_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` VARCHAR(64) NOT NULL,
    `document_id` BIGINT NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `stage` VARCHAR(32) NOT NULL,
    `progress` INT NOT NULL DEFAULT 0,
    `message` VARCHAR(1024) NULL,
    `error_message` TEXT NULL,
    `cancel_requested` TINYINT NOT NULL DEFAULT 0,
    `parameters` JSON NULL,
    `segment_count` INT NOT NULL DEFAULT 0,
    `embedded_count` INT NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ingestion_task_id` (`task_id`),
    INDEX `idx_ingestion_document_id` (`document_id`),
    INDEX `idx_ingestion_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Document ingestion background tasks';

CREATE TABLE IF NOT EXISTS `car_info` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `info_id` VARCHAR(64) NOT NULL COMMENT '车型唯一标识',
    `brand` VARCHAR(64) DEFAULT NULL COMMENT '品牌',
    `model_name` VARCHAR(128) DEFAULT NULL COMMENT '型号名称',
    `model_year` INT DEFAULT NULL COMMENT '年款',
    `version` VARCHAR(128) DEFAULT NULL COMMENT '版本描述',
    `full_name` VARCHAR(256) DEFAULT NULL COMMENT '全称',
    `vehicle_type` VARCHAR(32) DEFAULT NULL COMMENT '车辆类型',
    `fuel_type` VARCHAR(32) DEFAULT NULL COMMENT '燃油类型',
    `seat_count` INT DEFAULT NULL COMMENT '座位数',
    `displacement` DECIMAL(4,1) DEFAULT NULL COMMENT '排量',
    `motor_power` DECIMAL(8,2) DEFAULT NULL COMMENT '电机功率',
    `range_km` INT DEFAULT NULL COMMENT '续航里程',
    `guide_price` DECIMAL(12,2) DEFAULT NULL COMMENT '官方指导价',
    `color_options` VARCHAR(512) DEFAULT NULL COMMENT '车身颜色选项',
    `dimensions` VARCHAR(64) DEFAULT NULL COMMENT '车身尺寸',
    `wheelbase` INT DEFAULT NULL COMMENT '轴距',
    `manufacturer` VARCHAR(128) DEFAULT NULL COMMENT '生产厂商',
    `status` VARCHAR(32) DEFAULT '在售' COMMENT '车型状态',
    `image_url` VARCHAR(512) DEFAULT NULL COMMENT '车型图片URL',
    `description` TEXT DEFAULT NULL COMMENT '车型描述',
    `remark` TEXT DEFAULT NULL COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_info_id` (`info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='车型信息表';

CREATE TABLE IF NOT EXISTS `my_car` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `car_id` VARCHAR(64) NOT NULL COMMENT '车辆唯一标识',
    `user_id` VARCHAR(64) DEFAULT NULL COMMENT '用户ID',
    `car_info_id` VARCHAR(64) DEFAULT NULL COMMENT '关联的车型信息ID',
    `nickname` VARCHAR(128) DEFAULT NULL COMMENT '车辆昵称',
    `full_name` VARCHAR(256) DEFAULT NULL COMMENT '车辆全称',
    `image_url` VARCHAR(512) DEFAULT NULL COMMENT '车辆图片URL',
    `order_id` VARCHAR(64) DEFAULT NULL COMMENT '关联的购车订单ID',
    `plate_number` VARCHAR(32) NOT NULL COMMENT '车牌号',
    `color` VARCHAR(32) DEFAULT NULL COMMENT '车辆颜色',
    `vin` VARCHAR(32) DEFAULT NULL COMMENT '车辆识别代号',
    `engine_number` VARCHAR(64) DEFAULT NULL COMMENT '发动机号',
    `purchase_date` DATE DEFAULT NULL COMMENT '购买日期',
    `purchase_price` DECIMAL(15,2) DEFAULT NULL COMMENT '购买价格',
    `mileage` INT DEFAULT 0 COMMENT '行驶里程',
    `register_date` DATE DEFAULT NULL COMMENT '注册日期',
    `insurance_expire_date` DATE DEFAULT NULL COMMENT '保险到期日',
    `inspection_expire_date` DATE DEFAULT NULL COMMENT '年检到期日',
    `remark` TEXT DEFAULT NULL COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_car_id` (`car_id`),
    UNIQUE KEY `uk_plate_number` (`plate_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='我的车辆信息表';

CREATE TABLE IF NOT EXISTS `car_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` VARCHAR(64) NOT NULL COMMENT '订单唯一标识',
    `user_id` VARCHAR(64) DEFAULT NULL COMMENT '用户ID',
    `car_id` VARCHAR(64) DEFAULT NULL COMMENT '关联的车辆ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单编号',
    `order_type` VARCHAR(32) DEFAULT NULL COMMENT '订单类型',
    `order_status` VARCHAR(32) DEFAULT '待支付' COMMENT '订单状态',
    `brand` VARCHAR(64) DEFAULT NULL COMMENT '车辆品牌',
    `model` VARCHAR(128) DEFAULT NULL COMMENT '车辆型号',
    `color` VARCHAR(32) DEFAULT NULL COMMENT '车辆颜色',
    `vin` VARCHAR(32) DEFAULT NULL COMMENT '车辆VIN码',
    `seller_name` VARCHAR(256) DEFAULT NULL COMMENT '卖家或经销商名称',
    `seller_contact` VARCHAR(128) DEFAULT NULL COMMENT '卖家或经销商联系方式',
    `vehicle_price` DECIMAL(15,2) DEFAULT NULL COMMENT '车辆价格',
    `purchase_tax` DECIMAL(15,2) DEFAULT NULL COMMENT '购置税',
    `insurance_fee` DECIMAL(15,2) DEFAULT NULL COMMENT '保险费用',
    `other_fee` DECIMAL(15,2) DEFAULT NULL COMMENT '其他费用',
    `total_amount` DECIMAL(15,2) DEFAULT NULL COMMENT '订单总金额',
    `discount_amount` DECIMAL(15,2) DEFAULT NULL COMMENT '优惠金额',
    `actual_amount` DECIMAL(15,2) DEFAULT NULL COMMENT '实际支付金额',
    `payment_method` VARCHAR(32) DEFAULT NULL COMMENT '付款方式',
    `order_date` DATE DEFAULT NULL COMMENT '订单日期',
    `delivery_date` DATE DEFAULT NULL COMMENT '交付日期',
    `remark` TEXT DEFAULT NULL COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_id` (`order_id`),
    UNIQUE KEY `uk_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='车辆订单表';
